<?php
include_once 'src/config/base_url.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/pifano-inmobiliaria/public/output.css?v=1.0.3">
    <link rel="stylesheet" href="/pifano-inmobiliaria/src/css/styles.css">
    <link rel="icon" type="image/png" href="/pifano-inmobiliaria/public/images/pifanologo.jpg"/>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Pifano Inmobiliaria</title>
    <base href="'.BASE_URL.'">
</head>
<body>