<?php include_once 'src/templates/header.phtml'; ?>


<main class="min-h-screen bg-red-100 w-full flex flex-col justify-center items-center gap-4 py-12">
    <h1 class="text-red-600 font-bold">Error 404</h1>
    <h6>Pagina no encontrada</h6>
    <a href="/pifano-inmobiliaria" class="text-red-600 border-2 border-red-600 rounded-md px-4 py-2 no-underline hover:text-red-800">Regresar al inicio</a>
</main>

<?php include_once 'src/templates/footer.phtml'; ?>