<?php include_once 'src/templates/header.phtml'; ?>

<main class="min-h-screen bg-indigo-100 w-full grid items-start gap-4 py-4">

    <div class="w-full flex justify-between items-center px-8 mb-4">
        <a href="/pifano-inmobiliaria" 
        class="text-red-600 border-2 border-red-600 rounded-md px-4 py-2 no-underline hover:text-red-800">
            Regresar al inicio
        </a>

        <a href="/pifano-inmobiliaria/crear-propiedad" 
        class="text-green-600 border-2 border-green-600 rounded-md px-4 py-2 no-underline hover:text-green-800">
            Crear propiedad
        </a>
    </div>

    <div class="container flex justify-center mx-auto mt-2">
        <div class="flex flex-col w-full px-4">

            <div class="border-b border-gray-200 shadow">
                <table class="divide-y divide-gray-300 w-full">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-4 py-2 text-xs text-gray-500">ID</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Ciudad</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Dirección</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Piso</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Departamento</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Descripción</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Tipo</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Precio Base</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Acciones</th>
                            <th class="px-4 py-2 text-xs text-gray-500">Acciones</th>
                        </tr>
                    </thead>

                    <tbody class="bg-white divide-y divide-gray-300">
                        <?php foreach ($properties as $p): ?>
                            <tr class="whitespace-nowrap">
                                <td class="px-4 py-3"><?= $p->id_property?></td>
                                <td class="px-4 py-3"><?= $p->city ?></td>
                                <td class="px-4 py-3"><?= $p->address ?></td>
                                <td class="px-4 py-3"><?= $p->floor ?></td>
                                <td class="px-4 py-3"><?= $p->apartment ?></td>
                                <td class="px-4 py-3"><?= $p->description ?></td>
                                <td class="px-4 py-3"><?= $p->type ?></td>
                                <td class="px-4 py-3"><?= $p->base_price ?></td>

                                <td class="px-4 py-3">
                                    <a href="/pifano-inmobiliaria/editar-propiedad/<?= $p->id_property ?>" 
                                    class="px-3 py-1 text-sm text-indigo-600 bg-indigo-200 rounded-full">
                                            Editar
                                     </a>
                                </td>

                                <td class="px-4 py-3">
                                    <a onclick="return confirm('¿Seguro que deseas eliminar esta propiedad?');"
                                        href="?action=eliminar-propiedad/<?= $p->id_property ?>"
                                        class="px-3 py-1 text-sm text-red-400 bg-red-200 rounded-full">
                                        Eliminar
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
            </div>

        </div>
    </div>

</main>


<?php include_once 'src/templates/footer.phtml'; ?>
