<?php include_once 'src/templates/header.phtml'; ?>

<main class="min-h-screen bg-indigo-100 w-full grid items-start py-8">
    <div class="max-w-2xl mx-auto bg-white shadow-md rounded-lg p-8">
        <h2 class="text-2xl font-semibold mb-6 text-indigo-700">Informar pago</h2>

        <form action="<?= BASE_URL ?>informar-pago" method="POST">
            <input type="hidden" name="id_rent" id="id_rent" value="<?= $id_rent ?>">

            <div class="mb-4">
                <label class="text-gray-700">Monto</label>
                <input type="number" name="amount" required class="w-full border border-gray-300 rounded-md px-4 py-2" />
            </div>
            <div>
                <label class="text-gray-700">Fecha de generación</label>
                <input type="date" name="issued_date" required class="w-full border border-gray-300 rounded-md px-4 py-2" />
            </div>

            <div class="inline-flex justify-between gap-1 w-full">
                <a href="<?= BASE_URL ?>control-alquiler/<?= $id_rent ?>" class="w-full text-center bg-indigo-200 text-indigo-600 px-4 py-2 rounded-md mt-4">
                    Regresar
                </a>
                <button class="w-full bg-indigo-600 text-white px-4 py-2 rounded-md mt-4">
                    Guardar
                </button>
            </div>

        </form>

    </div>
</main>

<?php include_once 'src/templates/footer.phtml'; ?>