<?php include_once 'src/templates/header.phtml'; ?>


<main class="min-h-screen bg-indigo-100 w-full flex flex-col items-start gap-4 py-12">
    <div class="container flex justify-center mx-auto">
        <div class="flex flex-col w-4/5 md:w-3/4">
            <div class="w-full justify-between flex">
                <a href="<?= BASE_URL ?>inicio" class="no-underline text-red-600 border-2 p-2 rounded-md border-red-600">Regresar al inicio</a>
                <a href="<?= BASE_URL ?>crear-alquiler" class="no-underline text-green-600 border-2 p-2 rounded-md border-green-600">Crear alquiler</a>
            </div>
        </div>
    </div>

    <div class="container flex justify-center mx-auto">
        <div class="flex flex-col">
            <div class="w-full">
                <div class="border-b border-gray-200 shadow">
                    <table class="divide-y divide-gray-300 ">
                        <thead class="bg-gray-50">
                            <tr>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    ID
                                </th>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    Inquilino
                                </th>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    Dirección
                                </th>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    Firmado el
                                </th>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    Precio
                                </th>
                                <th class="px-6 py-2 text-xs text-gray-500">
                                    Herramientas
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-300">
                            <tr class="whitespace-nowrap">
                                <td class="px-6 py-4 text-sm text-gray-500">
                                    1
                                </td>
                                <td class="px-6 py-4">
                                    <div class="text-sm text-gray-900">
                                        Jon doe
                                    </div>
                                </td>
                                <td class="px-6 py-4">
                                    <div class="text-sm text-gray-500">Av 25 de Mayo 1039</div>
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-500">
                                    2021-1-12
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-500">
                                    $200.000
                                </td>
                                <td class="px-6 py-4">
                                    <a href="/pifano-inmobiliaria/alquileres/editar/{id}" class="px-4 py-1 text-sm text-indigo-600 bg-indigo-200 rounded-full">Editar</a>
                                    <a href="/pifano-inmobiliaria/alquileres/eliminar/{id}" class="px-4 py-1 text-sm text-red-400 bg-red-200 rounded-full">Eliminar</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>


<?php include_once 'src/templates/footer.phtml'; ?>